apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ .Release.Name }}-admission-patch
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ .Release.Name }}-admission-patch
spec:
  template:
    metadata:
      name:  {{ .Release.Name }}-admission-patch
      labels:
        app: {{ .Release.Name }}-admission-patch
    spec:
      containers:
      - name: patch
        image: jettech/kube-webhook-certgen:v1.5.2
        imagePullPolicy: IfNotPresent
        args:
        - patch
        - --webhook-name={{ .Values.webhook.name }}
        - --namespace={{ .Release.Namespace }}
        - --secret-name={{ .Values.webhook.secret }}
        - --patch-failure-policy={{ .Values.webhook.failurePolicy }}
        - --patch-mutating={{ .Values.webhook.mutating }}
        - --patch-validating={{ .Values.webhook.validating }}
        - --log-level={{ .Values.logLevel }}
      restartPolicy: OnFailure
      serviceAccountName: {{ .Release.Name }}-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
