apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ .Release.Name }}-admission-create
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ .Release.Name }}-admission-create
spec:
  template:
    metadata:
      name:  {{ .Release.Name }}-admission-create
      labels:
        app: {{ .Release.Name }}-admission-create
    spec:
      containers:
      - name: create
        image: jettech/kube-webhook-certgen:{{ .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        args:
        - create
        - --host={{ .Values.webhook.service }},{{ .Values.webhook.service }}.{{ .Release.Namespace }}.svc
        - --namespace={{ .Release.Namespace }}
        - --secret-name={{ .Values.webhook.secret }}
      restartPolicy: OnFailure
      serviceAccountName: {{ .Release.Name }}-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
